project/api/urls.py
from django.conf.urls import url

from api import views


urlpatterns = [
    url(r'^categories/$', views.CategoryListAPIView.as_view(), name='category_list_api'),
    url(r'^categories/(?P<pk>\d+)/$', views.CategoryRetrieveAPIView.as_view(), name='category_retrieve_api'),
    url(r'^subcategories/$', views.SubCategoryListAPIView.as_view(), name='subcategory_list_api'),
    url(r'^subcategories/(?P<pk>\d+)/$', views.SubCategoryRetrieveAPIView.as_view(), name='subcategories_retrieve_api'),
    url(r'^category/posts/$', views.CategoryPostsListAPIView.as_view(), name='category_posts_list_api'),
    url(r'^subcategory/posts/$', views.SubCategoryPostsListAPIView.as_view(), name='subcategory_post_list_api'),
    url(r'^category/(?P<pk>\d+)/posts/$', views.CategoryPostsRetrieveAPIView.as_view(), name='category_posts_retrieve_api'),
    url(r'^subcategory/(?P<pk>\d+)/posts/$', views.SubCategoryPostsRetrieveAPIView.as_view(), name='subcategory_posts_retrieve_api'),
    url(r'^posts/$', views.PostListCreateAPIView.as_view(), name='post_list_create_api'),
    url(r'post/(?P<pk>\d+)/$', views.PostRetrieveUpdateAPIView.as_view(), name='post_retrieve_update_api'),
]

project/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_view
from django.views.static import serve
from django.contrib.auth.decorators import login_required

from main import views
from .settings import MEDIA_ROOT


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^media/(?P<path>.*)/$', serve, {'document_root': MEDIA_ROOT}),
    url(r'^signup/$', views.UserCreate.as_view(), name='signup'),
    url(r'^accounts/login/$', auth_view.login, name='login'),
    url(r'^accounts/logout/$', auth_view.logout_then_login, name='logout'),
    url(r'^update/city/(?P<pk>\d+)/$', views.UpdateCity.as_view(), name='update_city'),
    url(r'^home/$', views.Home.as_view(), name='home'),
    url(r'^subcategory/thumbnail/(?P<pk>\d+)/$', views.SubCategoryThumbnailDetail.as_view(), name='subcategory_thumbnail'),
    url(r'^subcategory/list/(?P<pk>\d+)/$', views.SubCategoryList.as_view(), name='subcategory_list'),
    url(r'^subcategory/gallery/(?P<pk>\d+)/$', views.SubCategoryGallery.as_view(), name='subcategory_gallery'),
    url(r'^subcategory/posts/(?P<pk>\d+)/$', views.PostDetail.as_view(), name='post_detail'),
    url(r'^subcategory/create/post/(?P<post_id>\d+)/$', login_required(views.CreatePost.as_view()), name='create_post'),
    url(r'^subcategory/highest/price/(?P<pk>\d+)/$', views.SubCategoryHighestPrice.as_view(), name='subcategory_highest'),
    url(r'^subcategory/lowest/price/(?P<pk>\d+)/$', views.SubCategoryLowestPrice.as_view(), name='subcategory_lowest'),
    url(r'^api/', include('api.urls')),
]

project/main/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    city = models.CharField(max_length=128, null=True)


class Category(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class SubCategory(models.Model):
    title = models.CharField(max_length=255)
    category = models.ForeignKey(Category)

    def __str__(self):
        return self.title


class Post(models.Model):
    subcategory = models.ForeignKey(SubCategory)
    user = models.ForeignKey(User)
    title = models.CharField(max_length=255)
    description = models.TextField()
    price = models.FloatField()
    image = models.ImageField(upload_to="img", null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    city = models.CharField(max_length=128)

    def __str__(self):
        return self.title

project/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    city = forms.CharField()

project/main/views.py
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import TemplateView, ListView, DetailView
from django.core.urlresolvers import reverse
from rest_framework.authtoken.models import Token

from .models import Category, SubCategory, Post, UserProfile
from .forms import UserCreateForm


class Index(TemplateView):
    """First page user sees when accessing website"""
    template_name = 'main/index.html'


class Home(ListView):
    """First page when user logs in"""
    model = Category
    template_name = 'main/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['token'] = Token.objects.get(user=self.request.user)
        return context


class SubCategoryThumbnailDetail(DetailView):
    model = SubCategory
    template_name = 'main/subcategory_thumbnail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['newest'] = Post.objects.filter(subcategory=self.kwargs['pk'])
        return context


class SubCategoryHighestPrice(DetailView):
    model = SubCategory
    template_name = 'main/subcategory_highest_price.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['highest'] = Post.objects.filter(subcategory=self.kwargs['pk']).order_by('-price')
        return context


class SubCategoryLowestPrice(DetailView):
    model = SubCategory
    template_name = 'main/subcategory_lowest_price.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lowest'] = Post.objects.filter(subcategory=self.kwargs['pk']).order_by('price')
        return context


class SubCategoryList(SubCategoryThumbnailDetail):
    template_name = 'main/subcategory_list.html'


class SubCategoryGallery(SubCategoryThumbnailDetail):
    template_name = 'main/subcategory_gallery.html'


class PostDetail(DetailView):
    model = Post


class CreatePost(CreateView):
    model = Post
    fields = ['title', 'description', 'price', 'image', 'city']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.subcategory = SubCategory.objects.get(pk=self.kwargs['post_id'])
        post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('home')


class UserCreate(CreateView):
    model = User
    form_class = UserCreateForm

    def form_valid(self, form):
        new_user = form.save(commit=False)
        new_user.user = self.request.user
        new_user.save()
        UserProfile.objects.create(user=new_user, city=form.cleaned_data['city'])
        Token.objects.create(user=new_user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('login')


class UpdateCity(UpdateView):
    model = UserProfile
    fields = ['city']

    def get_success_url(self):
        return reverse('home')

project/templates/main/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="container">
  <h3>Welcome {{ request.user }}</h3>
  <h4>You are looking in {{ request.user.userprofile.city }}</h4>
  <h4>Here is your API Auth Token: {{ token }}</h4>
  <ul>
  {% for category in object_list %}
    <li>{{ category.title }}</li>
    <ul>
    {% for subcategory in category.subcategory_set.all %}
    <a href="{% url 'subcategory_thumbnail' subcategory.id  %}"><li>{{ subcategory.title }}</a></li>
    {% endfor %}
    </ul>
  {% endfor %}
  </ul>
</div>
{% endblock %}

project/templates/main/index.html
{% extends 'base.html' %}

{% block title %}Cylon List{% endblock title %}

{% block content %}
<div class="container">
  <div class="jumbotron text-center">
    <h1>Welcome to Cylons List</h1>
  </div>
</div>
{% endblock %}

project/templates/main/post_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
<div class="container">
  <h3>Title: {{ object.title }}</h3>
  <div><strong>Description: </strong>{{ object.description }}</strong></div>
  <div><strong>Price: </strong>{{ object.price }}</div>
  {% if object.image %}
    <img src="{{ object.image.url }}">
  {% endif %}
  <div>{{ object.city }}</div>
  <div><em>{{ object.created }}</em></div>
</div>
{% endblock %}

project/templates/main/post_form.html
{% extends 'base.html'%}
{% load bootstrap_tags %}
{% block title %}Create Post{% endblock title %}

{% block content %}
<div class="container">
  <h3>Create a Post</h3>
  <form method="post" action="">
    {% csrf_token %}
    {{ form | as_bootstrap }}
    <input type="submit" value="Create Post" class="btn btn-info">
  </form>
</div>
{% endblock %}

project/templates/main/subcategory_gallery.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}
<div class="container">
  <ol class="breadcrumb">
    <p>Display: </p>
      <li><a href="{% url 'subcategory_list' object.id %}">List</a></li>
      <li><a href="{% url 'subcategory_thumbnail' object.id %}">Thumbnail</a></li>
      <li><a href="{% url 'subcategory_gallery' object.id %}">Gallery</a></li>
	</ol>
  <ol class="breadcrumb pull-right">
    <p>Order: </p>
    <li><a href="{% url 'subcategory_list' object.id %}">Newest</a></li>
    <li><a href="{% url 'subcategory_highest' object.id  %}">Highest Compensation</a></li>
    <li><a href="{% url 'subcategory_lowest' object.id  %}">Lowest Compensation</a></li>
	</ol>
  <a href="{% url 'create_post' object.pk %}" class="btn btn-info">Create Post</a>
  <br><br>
  {% for post in newest %}
    <a href="{% url 'post_detail' post.id  %}">{{ post.title | linebreaks }}</a>
    {% if post.image %}
      <img src="{{ post.image.url }}">
    {% endif %}
    <br><br>
  {% endfor %}
</div>
{% endblock %}

project/templates/main/subcategory_highest_price.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}
<div class="container">
  <ol class="breadcrumb">
    <p>Display: </p>
      <li><a href="{% url 'subcategory_list' object.id %}">List</a></li>
      <li><a href="{% url 'subcategory_thumbnail' object.id %}">Thumbnail</a></li>
      <li><a href="{% url 'subcategory_gallery' object.id %}">Gallery</a></li>
	</ol>
  <ol class="breadcrumb pull-right">
    <p>Order: </p>
    <li><a href="{% url 'subcategory_list' object.id %}">Newest</a></li>
    <li><a href="{% url 'subcategory_highest' object.id  %}">Highest Compensation</a></li>
    <li><a href="{% url 'subcategory_lowest' object.id  %}">Lowest Compensation</a></li>
	</ol>
  <a href="{% url 'create_post' object.pk %}" class="btn btn-info">Create Post</a>
  <br><br>
  {% for post in highest %}
    <a href="{% url 'post_detail' post.id  %}">{{ post.title | linebreaks }}</a>
    {{ post.price }}
    <br><br>
  {% endfor %}
</div>
{% endblock %}

project/templates/main/subcategory_list.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}
<div class="container">
  <ol class="breadcrumb">
    <p>Display: </p>
      <li><a href="{% url 'subcategory_list' object.id %}">List</a></li>
      <li><a href="{% url 'subcategory_thumbnail' object.id %}">Thumbnail</a></li>
      <li><a href="{% url 'subcategory_gallery' object.id %}">Gallery</a></li>
	</ol>
  <ol class="breadcrumb pull-right">
    <p>Order: </p>
    <li><a href="{% url 'subcategory_list' object.id %}">Newest</a></li>
    <li><a href="{% url 'subcategory_highest' object.id  %}">Highest Compensation</a></li>
    <li><a href="{% url 'subcategory_lowest' object.id  %}">Lowest Compensation</a></li>
	</ol>
  <a href="{% url 'create_post' object.pk %}" class="btn btn-info">Create Post</a>
  <br><br>
  {% for post in newest %}
    <a href="{% url 'post_detail' post.id  %}">{{ post.title | linebreaks }}</a>
    {{ post.price }}
    <br><br>
  {% endfor %}
</div>
{% endblock %}

project/templates/main/subcategory_lowest_price.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}
<div class="container">
  <ol class="breadcrumb">
    <p>Display: </p>
      <li><a href="{% url 'subcategory_list' object.id %}">List</a></li>
      <li><a href="{% url 'subcategory_thumbnail' object.id %}">Thumbnail</a></li>
      <li><a href="{% url 'subcategory_gallery' object.id %}">Gallery</a></li>
	</ol>
  <ol class="breadcrumb pull-right">
    <p>Order: </p>
    <li><a href="{% url 'subcategory_list' object.id %}">Newest</a></li>
    <li><a href="{% url 'subcategory_highest' object.id  %}">Highest Compensation</a></li>
    <li><a href="{% url 'subcategory_lowest' object.id  %}">Lowest Compensation</a></li>
	</ol>
  <a href="{% url 'create_post' object.pk %}" class="btn btn-info">Create Post</a>
  <br><br>
  {% for post in lowest %}
    <a href="{% url 'post_detail' post.id  %}">{{ post.title | linebreaks }}</a>
    {{ post.price }}
    <br><br>
  {% endfor %}
</div>
{% endblock %}

project/templates/main/subcategory_thumbnail.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}
<div class="container">
  <ol class="breadcrumb">
    <p>Display: </p>
    <li><a href="{% url 'subcategory_list' object.id %}">List</a></li>
    <li><a href="{% url 'subcategory_thumbnail' object.id %}">Thumbnail</a></li>
    <li><a href="{% url 'subcategory_gallery' object.id %}">Gallery</a></li>
	</ol>
  <ol class="breadcrumb pull-right">
    <p>Order: </p>
    <li><a href="{% url 'subcategory_list' object.id %}">Newest</a></li>
    <li><a href="{% url 'subcategory_highest' object.id  %}">Highest Compensation</a></li>
    <li><a href="{% url 'subcategory_lowest' object.id  %}">Lowest Compensation</a></li>
	</ol>
    <a href="{% url 'create_post' object.id %}" class="btn btn-info">Create Post</a>
  <br><br>
  {% for post in newest %}
    <a href="{% url 'post_detail' post.id  %}">{{ post.title | linebreaks }}</a>
    {{ post.price }}
    {% if post.image %}
      <img src="{{ post.image.url }}" height="80" width="80">
    {% endif %}
    <br><br>
  {% endfor %}
</div>
{% endblock %}

project/templates/main/userprofile_form.html
{% extends 'base.html' %}
{% load bootstrap_tags %}
{% block title %}Update City{% endblock title %}

{% block content %}
<div class="container">
  <form method="post" action="">
    {% csrf_token %}
    {{ form | as_bootstrap }}
    <input type="submit" value="Update City" class="btn btn-info">
  </form>
</div>
{% endblock %}